version: '3.4'

name: "ibge-site"

services:
  ibgeblazor.web:
    container_name: web-frontend
    image: ${DOCKER_REGISTRY-}ibgeblazorweb
    build:
      context: .
      dockerfile: src/IbgeBlazor.Web/IbgeBlazor.Web/Dockerfile
    ports:
        - "8085:80"
    depends_on:
        - ibgeblazor.api
  ibgeblazor.api:
    container_name: web-api
    image: ${DOCKER_REGISTRY-}ibgeblazorapi
    build:
      context: .
      dockerfile: src/IbgeBlazor.Api/Dockerfile
    depends_on:
        - sqlserver
  sqlserver:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "1q2w3e4r@#$"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer"
    ports:
        - "1433:1433"
    volumes:
     - /c/data:/var/opt/mssql/data