// <auto-generated />
using IbgeBlazor.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IbgeBlazor.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231220011421_UpdateStateIdentityV4")]
    partial class UpdateStateIdentityV4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(7)
                        .HasColumnType("char")
                        .HasColumnName("CODIGO_MUNICIPIO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("NOME_MUNICIPIO");

                    b.Property<int>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("UF_ID");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.HasIndex(new[] { "Name" }, "IX_MUNICIPIOS_NOME_MUNICIPIO");

                    b.ToTable("MUNICIPIOS", (string)null);
                });

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("CODIGO_ESTADO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("NOME_ESTADO");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "IX_ESTADOS_CODIGO_ESTADO")
                        .IsUnique();

                    b.ToTable("ESTADOS", (string)null);
                });

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.City", b =>
                {
                    b.HasOne("IbgeBlazor.Core.LocalityContext.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
