// <auto-generated />
using IbgeBlazor.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IbgeBlazor.Infraestructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231216223700_MapCities")]
    partial class MapCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(7)
                        .HasColumnType("Char")
                        .HasColumnName("CODIGO_MUNICIPIO");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VarChar")
                        .HasColumnName("NOME_MUNICIPIO");

                    b.Property<int>("StateId")
                        .HasColumnType("Int")
                        .HasColumnName("CODIGO_UF");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.HasIndex(new[] { "CityName" }, "IX_MUNICIPIOS_NOME_MUNICIPIO");

                    b.ToTable("MUNICIPIOS", (string)null);
                });

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("Char")
                        .HasColumnName("CODIGO_ESTADO");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VarChar")
                        .HasColumnName("NOME_ESTADO");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "IX_ESTADOS_CODIGO_ESTADO");

                    b.ToTable("ESTADOS", (string)null);
                });

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.City", b =>
                {
                    b.HasOne("IbgeBlazor.Core.LocalityContext.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
