// <auto-generated />
using IbgeBlazor.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IbgeBlazor.Infraestructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IbgeBlazor.Core.LocalityContext.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("Char")
                        .HasColumnName("CODIGO_ESTADO");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VarChar")
                        .HasColumnName("NOME_ESTADO");

                    b.HasKey("Id", "Code");

                    b.HasIndex(new[] { "Code" }, "IX_ESTATDOS_CODIGO_ESTADO");

                    b.ToTable("ESTADOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
